/** Etiquetas en espanol para paths de validacion Zod. */
import { INADMISSIBILITY_QUESTIONS } from "../inadmissibilityQuestions";

const INAD_FIELD_LABELS = Object.fromEntries(
  INADMISSIBILITY_QUESTIONS.map((item) => [
    `caseBackground.${item.field}`,
    `Inadmisibilidad (${item.number})`,
  ])
);

export const FIELD_LABELS: Record<string, string> = {
  "personalData.nombres": "Primer nombre",
  "personalData.segundoNombre": "Segundo nombre",
  "personalData.apellidoPaterno": "Apellido paterno",
  "personalData.apellidoMaterno": "Apellido materno",
  "personalData.otrosNombres": "Otros nombres",
  "personalData.fechaNacimiento": "Fecha de nacimiento",
  "personalData.ciudadNacimiento": "Ciudad de nacimiento",
  "personalData.estadoNacimiento": "Estado / provincia de nacimiento",
  "personalData.paisNacimiento": "Pais de nacimiento",
  "personalData.sexo": "Sexo",
  "personalData.estadoCivil": "Estado civil",
  "personalData.nacionalidad": "Nacionalidad",
  "personalData.comprendeIngles": "Comprende ingles",
  "personalData.idiomaPreferido": "Idioma preferido",
  "personalData.hablaOtroIdioma": "Habla otro idioma",
  "personalData.especificarIdioma": "Especificar idioma",
  "contact.telefono": "Telefono de contacto",
  "contact.correoElectronico": "Correo electronico",
  "address.calleNumero": "Calle y numero",
  "address.aptoSuite": "Apto / Suite",
  "address.ciudad": "Ciudad",
  "address.estado": "Estado",
  "address.codigoPostal": "Codigo postal",
  "address.pais": "Pais",
  "address.fechaIngreso": "Fecha de ingreso a esta direccion",
  "address.resididoOtrosLugares": "Ha residido en otros lugares",
  "documents.tienePasaporte": "Cuenta con pasaporte",
  "documents.pasaportePendiente": "Pasaporte pendiente",
  "documents.numeroPasaporte": "Numero de pasaporte",
  "documents.paisEmision": "Pais de emision",
  "documents.fechaEmision": "Fecha de emision del pasaporte",
  "documents.fechaExpiracion": "Fecha de expiracion del pasaporte",
  "documents.tieneANumber": "Tiene A-Number",
  "documents.aNumberValue": "A-Number",
  "documents.aNumberOrigen": "Origen del A-Number",
  "documents.tieneSSN": "Tiene SSN",
  "documents.ssnValue": "SSN",
  "documents.tieneEAD": "Tiene EAD",
  "documents.eadValue": "Numero de EAD",
  "family.tieneConyuge": "Tiene conyuge",
  "family.nombresConyuge": "Nombre(s) del conyuge",
  "family.segundoNombreConyuge": "Segundo nombre del conyuge",
  "family.apellidoPaternoConyuge": "Apellido paterno del conyuge",
  "family.apellidoMaternoConyuge": "Apellido materno del conyuge",
  "family.fechaLugarMatrimonioConyuge": "Fecha y lugar de matrimonio",
  "family.fechaLugarNacimientoConyuge": "Fecha y lugar de nacimiento del conyuge",
  "family.nombresPadre": "Nombre(s) del padre",
  "family.segundoNombrePadre": "Segundo nombre del padre",
  "family.apellidoPaternoPadre": "Apellido paterno del padre",
  "family.apellidoMaternoPadre": "Apellido materno del padre",
  "family.nombresMadre": "Nombre(s) de la madre",
  "family.segundoNombreMadre": "Segundo nombre de la madre",
  "family.apellidoPaternoMadre": "Apellido paterno de la madre",
  "family.apellidoMaternoMadre": "Apellido materno de la madre",
  "family.casado": "Esta casado actualmente",
  "family.previamenteCasado": "Estuvo previamente casado",
  "family.tieneHijos": "Tiene hijos",
  "caseBackground.viajesComentarios": "Comentarios sobre viajes",
  "caseBackground.detenidoInmigracion": "Detenido por inmigracion",
  "caseBackground.arrestadoPolicia": "Arrestado por la policia",
  "caseBackground.empleoNombre": "Nombre del empleador",
  "caseBackground.empleoOcupacion": "Ocupacion",
  "caseBackground.empleoDireccionCalle": "Calle del empleo",
  "caseBackground.empleoDireccionApto": "Apto del empleo",
  "caseBackground.empleoDireccionCiudad": "Ciudad del empleo",
  "caseBackground.empleoDireccionEstado": "Estado del empleo",
  "caseBackground.empleoDireccionZip": "ZIP del empleo",
  "caseBackground.empleoDireccionPais": "Pais del empleo",
  "caseBackground.empleoFechaIngreso": "Fecha de ingreso al empleo",
  "caseBackground.empleoFechaSalida": "Fecha de salida del empleo",
  "caseBackground.empleoOtrosLugares": "Otros empleos",
  "caseBackground.inadMyUscisDetalle": "Detalles de myUSCIS",
  "caseBackground.declaradoCiudadano": "Declarado ciudadano",
  "caseBackground.falsaDeclaracionLugar": "Falsa declaracion (lugar)",
  "caseBackground.falsaDeclaracionFecha": "Falsa declaracion (fecha)",
  "caseBackground.falsaDeclaracionComo": "Falsa declaracion (como)",
  "caseBackground.falsaDeclaracionIntencion": "Falsa declaracion (intencion)",
  "caseBackground.falsaDeclaracionDetalle": "Falsa declaracion (detalle)",
  "caseBackground.documentosPendientes": "Documentos pendientes",
  "caseBackground.correosPendientes": "Correos pendientes",
  "caseBackground.foias.uscis.solicitar": "FOIA USCIS",
  "caseBackground.foias.uscis.motivo": "Motivo FOIA USCIS",
  "caseBackground.foias.ice.solicitar": "FOIA ICE",
  "caseBackground.foias.ice.motivo": "Motivo FOIA ICE",
  "caseBackground.foias.cbp.solicitar": "FOIA CBP",
  "caseBackground.foias.cbp.motivo": "Motivo FOIA CBP",
  "caseBackground.foias.eoir.solicitar": "FOIA EOIR",
  "caseBackground.foias.eoir.motivo": "Motivo FOIA EOIR",
  "caseBackground.foias.fbi.solicitar": "FOIA FBI",
  "caseBackground.foias.fbi.motivo": "Motivo FOIA FBI",
  "caseBackground.foias.policia.solicitar": "FOIA Policia",
  "caseBackground.foias.policia.motivo": "Motivo FOIA Policia",
  ...INAD_FIELD_LABELS,
};

const ARRAY_ITEM_LABELS: Record<string, string> = {
  direccionesAnteriores: "Direccion anterior",
  hijos: "Hijo",
  matrimoniosPrevios: "Matrimonio previo",
  viajes: "Viaje",
  detencionesInmi: "Detencion por inmigracion",
  arrestosPolicia: "Arresto policial",
  empleosAnteriores: "Empleo anterior",
};

const ARRAY_FIELD_LABELS: Record<string, string> = {
  calleNumero: "Calle y numero",
  aptoSuite: "Apto / Suite",
  ciudad: "Ciudad",
  estado: "Estado",
  codigoPostal: "Codigo postal",
  pais: "Pais",
  fechaDesde: "Desde",
  fechaHasta: "Hasta",
  nombres: "Nombre(s)",
  segundoNombre: "Segundo nombre",
  apellidoPaterno: "Apellido paterno",
  apellidoMaterno: "Apellido materno",
  fechaNacimiento: "Fecha de nacimiento",
  lugarNacimiento: "Lugar de nacimiento",
  lugarResidencia: "Lugar de residencia",
  nombresExConyuge: "Nombre(s) del ex-conyuge",
  segundoNombreExConyuge: "Segundo nombre del ex-conyuge",
  apellidoPaternoExConyuge: "Apellido paterno del ex-conyuge",
  apellidoMaternoExConyuge: "Apellido materno del ex-conyuge",
  fechaLugarMatrimonio: "Fecha y lugar de matrimonio",
  fechaLugarNacimiento: "Fecha y lugar de nacimiento",
  fechaLugarDivorcio: "Fecha y lugar de divorcio",
  fechaEntrada: "Fecha de entrada",
  formaEntrada: "Forma de entrada",
  lugarEntrada: "Lugar de entrada",
  fechaSalida: "Fecha de salida",
  fueDetenido: "Fue detenido",
  detallesDetencion: "Detalles de detencion",
  lugar: "Lugar",
  fecha: "Fecha",
  autoridad: "Autoridad",
  ordenDeportacion: "Orden de deportacion",
  sancionCastigo: "Sancion o castigo",
  regresoVoluntario: "Regreso voluntario",
  fotosHuellas: "Fotos y huellas",
  citaCorte: "Cita en corte",
  paisCiudadEstado: "Pais / Ciudad / Estado",
  motivo: "Motivo",
  disposicion: "Disposicion",
  empresa: "Empresa",
  puesto: "Puesto",
  direccionCalle: "Calle",
  direccionApto: "Apto",
  direccionCiudad: "Ciudad",
  direccionEstado: "Estado",
  direccionZip: "ZIP",
  direccionPais: "Pais",
};

export function getFieldLabel(path: string): string {
  if (FIELD_LABELS[path]) return FIELD_LABELS[path];

  const arrayMatch = path.match(/^(.+)\.(\w+)\.(\d+)\.(\w+)$/);
  if (arrayMatch) {
    const [, , arrayKey, index, field] = arrayMatch;
    const itemLabel = ARRAY_ITEM_LABELS[arrayKey] ?? arrayKey;
    const fieldLabel = ARRAY_FIELD_LABELS[field] ?? field;
    return `${itemLabel} #${Number(index) + 1} — ${fieldLabel}`;
  }

  const parts = path.split(".");
  const last = parts[parts.length - 1];
  return ARRAY_FIELD_LABELS[last] ?? last;
}
